// frontend/src/components/llm/LlmChatDialog.tsx
import { useState, useCallback } from 'react';
import { Modal, Button, Select, Input, Message } from '@arco-design/web-react';
import { marked } from 'marked';
import * as llmChatApi from '@/api/llm/llmChat';

interface ChatMessage {
  role: string;
  content: string;
}

const providerOptions = [
  { label: 'DeepSeek V3.2', value: 'deepseek' },
  { label: 'Kimi K2.5', value: 'moonshot' },
  { label: 'MiniMax-M2.1', value: 'minimax' },
];

interface LlmChatDialogProps {
  visible: boolean;
  onClose: () => void;
}

const LlmChatDialog = ({ visible, onClose }: LlmChatDialogProps) => {
  const [userMessage, setUserMessage] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState<string>('deepseek');

  const renderMarkdown = useCallback((text: string) => {
    return marked.parse(text || '') as string;
  }, []);

  const sendMessage = async () => {
    if (!userMessage.trim()) return;

    const input = userMessage;
    setMessages((prev) => [...prev, { role: 'user', content: input }]);
    setUserMessage('');
    setLoading(true);

    try {
      const res = await llmChatApi.sendChatMessage(input, selectedProvider);
      setMessages((prev) => [...prev, { role: 'ai', content: res.reply }]);
    } catch (err: any) {
      const errorMessage =
        err?.message ||
        err?.msg ||
        (typeof err === 'string' ? err : '') ||
        '请求失败，请稍后重试。';
      setMessages((prev) => [...prev, { role: 'ai', content: `⚠️ ${errorMessage}` }]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const handleClearContext = () => {
    Modal.confirm({
      title: '清空上下文确认',
      content: '确定要清空 AI 的上下文记忆吗？这会重置对话上下文。',
      okText: '确认',
      cancelText: '取消',
      onOk: async () => {
        try {
          const res = await llmChatApi.clearChatContext();
          setMessages([]);
          Message.success(res.data || '上下文已清空');
        } catch {
          Message.error('清空失败，请稍后重试');
        }
      },
    });
  };

  const handleClose = () => {
    onClose();
  };

  return (
    <Modal
      title="AI 聊天"
      visible={visible}
      onCancel={handleClose}
      style={{ width: 600 }}
      footer={[
        <Button key="close" onClick={handleClose}>
          关闭
        </Button>,
        <Button key="clear" status="warning" onClick={handleClearContext}>
          清空上下文
        </Button>,
        <Button key="send" type="primary" loading={loading} onClick={sendMessage}>
          发送
        </Button>,
      ]}
    >
      <div className="chat-header">
        <span className="chat-header-label">当前模型：</span>
        <Select
          value={selectedProvider}
          onChange={setSelectedProvider}
          style={{ width: 180 }}
          disabled={loading}
        >
          {providerOptions.map((item) => (
            <Select.Option key={item.value} value={item.value}>
              {item.label}
            </Select.Option>
          ))}
        </Select>
      </div>

      <div className="chat-box">
        <div className="chat-messages">
          {messages.map((msg, index) => (
            <div key={index} className={msg.role}>
              <span dangerouslySetInnerHTML={{ __html: renderMarkdown(msg.content) }} />
            </div>
          ))}
        </div>
        <Input.TextArea
          value={userMessage}
          onChange={setUserMessage}
          placeholder="请输入消息..."
          rows={3}
          disabled={loading}
          onKeyDown={handleKeyDown}
        />
      </div>
    </Modal>
  );
}

export default LlmChatDialog;

// ui-vue/src/components/llm/LlmChatDialog.vue
<!-- src/components/header/LlmChatDialog.vue -->
<template>
  <el-dialog v-model="visible" title="AI 聊天" width="600px">
    <div class="chat-header">
      <span class="chat-header-label">当前模型：</span>
      <el-select
          v-model="selectedProvider"
          size="small"
          style="width: 180px"
          :disabled="loading"
      >
        <el-option
            v-for="item in providerOptions"
            :key="item.value"
            :label="item.label"
            :value="item.value"
        />
      </el-select>
    </div>

    <div class="chat-box">
      <div class="chat-messages">
        <div
            v-for="(msg, index) in messages"
            :key="index"
            :class="msg.role"
        >
          <span v-html="renderMarkdown(msg.content)"></span>
        </div>
      </div>
      <el-input
          v-model="userMessage"
          type="textarea"
          placeholder="请输入消息..."
          @keyup.enter.native="sendMessage"
          rows="3"
          :disabled="loading"
      />
    </div>

    <template #footer>
      <el-button @click="visible = false">关闭</el-button>
      <el-button type="warning" plain @click="handleClearContext">清空上下文</el-button>
      <el-button type="primary" @click="sendMessage" :loading="loading">发送</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { marked } from 'marked';
import { ElMessage, ElMessageBox } from 'element-plus';
import * as llmChatApi from '@/api/llm/llmChat.ts'

const visible = ref(false);
const userMessage = ref('');
const messages = ref<{ role: string; content: string }[]>([]);
const loading = ref(false);

const providerOptions = [
  // DeepSeek
  { label: 'DeepSeek V3.2', value: 'deepseek' },
  // Moonshot (Kimi)
  { label: 'Kimi K2.5', value: 'moonshot' },
  // MiniMax
  { label: 'MiniMax-M2.1', value: 'minimax' }
];

const selectedProvider = ref<string>('deepseek');

// 打开对话框的方法（供外部调用）
const open = () => {
  visible.value = true;
};

// 发送消息
const sendMessage = async () => {
  if (!userMessage.value.trim()) return;

  // 1. 添加用户消息
  messages.value.push({ role: 'user', content: userMessage.value });
  const input = userMessage.value;
  userMessage.value = '';
  loading.value = true;

  try {
    // 2. 发送消息到后端
    const res = await llmChatApi.sendChatMessage(input, selectedProvider.value)
    // 3. 显示 AI 回复
    messages.value.push({ role: 'ai', content: res.reply });
  } catch (err: any) {
    // 从后端 Result 中提取更友好的错误信息
    const errorMessage =
        err?.message ||
        err?.msg ||
        (typeof err === 'string' ? err : '') ||
        '请求失败，请稍后重试。';
    messages.value.push({ role: 'ai', content: `⚠️ ${errorMessage}` });
  } finally {
    loading.value = false;
  }
};

// 清空上下文
const handleClearContext = async () => {
  try {
    await ElMessageBox.confirm(
        '确定要清空 AI 的上下文记忆吗？这会重置对话上下文。',
        '清空上下文确认',
        {
          type: 'warning',
          confirmButtonText: '确认',
          cancelButtonText: '取消',
        }
    );

    const res = await llmChatApi.clearChatContext()
    messages.value = [];
    ElMessage.success(res.data || '上下文已清空');
  } catch (err) {
    if (err !== 'cancel') {
      ElMessage.error('清空失败，请稍后重试');
    }
  }
};

// Markdown 渲染
const renderMarkdown = (text: string) => {
  return marked.parse(text || '');
};

// 让父组件可以调用 open()
defineExpose({ open });
</script>

<style scoped>
.chat-box {
  max-height: 400px;
  overflow-y: auto;
  margin-bottom: 10px;
}
.chat-messages {
  margin-bottom: 10px;
}
.user {
  text-align: right;
  margin: 5px 0;
  font-weight: bold;
}
.ai {
  text-align: left;
  margin: 5px 0;
  background: #f4f4f4;
  padding: 6px 10px;
  border-radius: 4px;
}
</style>
