// frontend/src/components/llm/LlmSummaryPostDialog.tsx
import { useState, useImperativeHandle, forwardRef } from 'react';
import { Modal, Button, Alert, Empty, Spin, Message } from '@arco-design/web-react';
import { IconRobot } from '@arco-design/web-react/icon';
import * as llmChatApi from '@/api/llm/llmChat';

interface LlmSummaryPostDialogProps {
  title: string;
  content: string;
}

export interface LlmSummaryPostDialogRef {
  open: () => void;
}

const LlmSummaryPostDialog = forwardRef<LlmSummaryPostDialogRef, LlmSummaryPostDialogProps>(
  (props, ref) => {
    const { title, content } = props;

    const [visible, setVisible] = useState(false);
    const [loading, setLoading] = useState(false);
    const [summary, setSummary] = useState('');
    const [error, setError] = useState('');

    useImperativeHandle(ref, () => ({
      open: () => {
        setVisible(true);
        setError('');
      },
    }));

    const handleGenerate = async () => {
      if (!title || !content) {
        Message.warning('文章标题或内容为空');
        return;
      }

      setLoading(true);
      setError('');
      setSummary('');

      try {
        const response = await llmChatApi.generatePostSummary(title, content);
        setSummary(response.summary);
        Message.success('AI 摘要生成成功');
      } catch (err) {
        console.error('生成 AI 摘要失败:', err);
        setError('生成摘要失败，请稍后重试');
        Message.error('生成摘要失败');
      } finally {
        setLoading(false);
      }
    };

    const handleClose = () => {
      setVisible(false);
      setSummary('');
      setError('');
    };

    return (
      <Modal
        title="AI 文章摘要"
        visible={visible}
        onCancel={handleClose}
        footer={[
          <Button key="close" onClick={handleClose}>
            关闭
          </Button>,
          <Button
            key="generate"
            type="primary"
            icon={<IconRobot />}
            loading={loading}
            disabled={loading}
            onClick={handleGenerate}
          >
            {summary ? '重新生成' : '生成摘要'}
          </Button>,
        ]}
      >
        <Spin loading={loading} className="summary-content">
          {error ? (
            <Alert type="error" content={error} />
          ) : summary ? (
            <div className="summary-text">{summary}</div>
          ) : (
            <Empty description="点击下方按钮生成 AI 摘要" />
          )}
        </Spin>
      </Modal>
    );
  }
);

export default LlmSummaryPostDialog;

// ui-vue/src/components/llm/LlmSummaryPostDialog.vue
<template>
  <el-dialog
      v-model="visible"
      title="AI 文章摘要"
      width="600px"
      :close-on-click-modal="false"
      @closed="handleClosed"
  >
    <div v-loading="loading" class="summary-content">
      <el-alert
          v-if="error"
          :title="error"
          type="error"
          :closable="false"
          show-icon
      />
      <div v-else-if="summary" class="summary-text">
        {{ summary }}
      </div>
      <el-empty v-else description="点击下方按钮生成 AI 摘要" />
    </div>
    <template #footer>
      <el-button @click="visible = false">关闭</el-button>
      <el-button
          type="primary"
          :icon="MagicStick"
          @click="handleGenerate"
          :loading="loading"
          :disabled="loading"
      >
        {{ summary ? '重新生成' : '生成摘要' }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { MagicStick } from '@element-plus/icons-vue'
import * as llmChatApi from '@/api/llm/llmChat.ts'

// Props
interface Props {
  title: string
  content: string
}

const props = defineProps<Props>()

// State
const visible = ref(false)
const loading = ref(false)
const summary = ref('')
const error = ref('')

// Methods
const open = () => {
  visible.value = true
  error.value = ''
}

const handleGenerate = async () => {
  if (!props.title || !props.content) {
    ElMessage.warning('文章标题或内容为空')
    return
  }

  loading.value = true
  error.value = ''
  summary.value = ''

  try {
    const response = await llmChatApi.generatePostSummary(props.title, props.content)
    summary.value = response.summary
    ElMessage.success('AI 摘要生成成功')
  } catch (err) {
    console.error('生成 AI 摘要失败:', err)
    error.value = '生成摘要失败，请稍后重试'
    ElMessage.error('生成摘要失败')
  } finally {
    loading.value = false
  }
}

const handleClosed = () => {
  // Reset state when dialog is closed
  summary.value = ''
  error.value = ''
}

// Expose methods for parent component
defineExpose({
  open
})
</script>

<style scoped>
.summary-content {
  min-height: 200px;
  padding: 20px 0;
}

.summary-text {
  font-size: 15px;
  line-height: 1.8;
  color: #303133;
  white-space: pre-wrap;
  word-wrap: break-word;
  background: #f5f7fa;
  padding: 20px;
  border-radius: 8px;
  border-left: 4px solid #67c23a;
}
</style>
