// frontend/src/views/post/RecommendFeed.vue
<template>
  <div class="recommend-feed-page">
    <PersonalizedFeed :refresh-ref="feedRef" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import PersonalizedFeed from '@/components/post/PersonalizedFeed.vue';
import './RecommendFeed.css';

const feedRef = ref<(() => void) | null>(null);
</script>

// frontend/src/pages/post/RecommendFeed.tsx
import { useRef } from 'react';
import PersonalizedFeed from '@/components/post/PersonalizedFeed';
import './RecommendFeed.css';

const RecommendFeed: React.FC = () => {
  const feedRef = useRef<(() => void) | null>(null);

  return (
    <div className="recommend-feed-page">
      <PersonalizedFeed refreshRef={feedRef} />
    </div>
  );
};

export default RecommendFeed;
