// ui-vue/src/views/profile/UserProfilePublic.vue
<template>
  <div class="user-profile-public">
    <el-card class="profile-header">
      <div class="profile-main">
        <div class="profile-avatar">
          <el-avatar :size="120" :src="getAvatarUrl(userProfile?.avatar)">
            {{ userProfile?.username?.charAt(0).toUpperCase() }}
          </el-avatar>
        </div>
        <div class="profile-info">
          <div class="profile-basic">
            <h2 class="profile-username">{{ userProfile?.username }}</h2>
            <div class="profile-stats">
              <div class="stat-item" @click="showFollowingList()">
                <span class="stat-number">{{ userStats.followingCount }}</span>
                <span class="stat-label">关注</span>
              </div>
              <div class="stat-item" @click="showFollowerList()">
                <span class="stat-number">{{ userStats.followerCount }}</span>
                <span class="stat-label">粉丝</span>
              </div>
              <div class="stat-item">
                <span class="stat-number">{{ postCount }}</span>
                <span class="stat-label">文章</span>
              </div>
            </div>
          </div>
          <div class="profile-actions">
            <el-button
                v-if="showFollowButton"
                :type="isFollowing ? 'danger' : 'primary'"
                :icon="Star"
                @click="toggleFollow"
                :loading="followLoading"
                size="large"
            >
              {{ isFollowing ? '取消关注' : '关注' }}
            </el-button>
            <el-button
                v-if="canChat"
                type="success"
                :icon="ChatDotRound"
                @click="startChat"
                size="large"
            >
              发消息
            </el-button>
          </div>
        </div>
      </div>
    </el-card>

    <el-card class="profile-content">
      <el-tabs v-model="activeTab" class="profile-tabs">

        <el-tab-pane label="文章" name="posts">
          <div class="tab-pane-container">
            <el-empty v-if="posts.length === 0" description="暂无文章"/>
            <div v-else class="posts-grid">
              <el-card
                  v-for="post in posts"
                  :key="post.id"
                  class="post-card"
                  @click="goToPostDetail(post.id)"
              >
                <h3 class="post-title">{{ post.title }}</h3>
                <div class="post-meta">
                  <span class="post-date">{{ formatDate(post.createdAt) }}</span>
                  <span class="post-stats">
                    <el-icon><View/></el-icon> {{ post.viewCount || 0 }}
                    <el-icon><ChatLineRound/></el-icon> {{ post.commentCount || 0 }}
                    <el-icon><Star/></el-icon> {{ post.likeCount || 0 }}
                  </span>
                </div>
                <div class="post-tags" v-if="post.tags && post.tags.length">
                  <el-tag
                      v-for="tag in post.tags"
                      :key="tag"
                      size="small"
                      type="info"
                      class="tag"
                  >
                    {{ tag }}
                  </el-tag>
                </div>
              </el-card>
            </div>

            <div class="pagination-wrapper" v-if="totalPosts > pageSize">
              <el-pagination
                  v-model:current-page="currentPage"
                  v-model:page-size="pageSize"
                  :total="totalPosts"
                  :page-sizes="[10, 20, 50]"
                  layout="total, sizes, prev, pager, next, jumper"
                  @size-change="handleSizeChange"
                  @current-change="handleCurrentChange"
              />
            </div>
          </div>
        </el-tab-pane>

        <el-tab-pane label="收藏" name="collects">
          <UserCollectList :user-id="userId" :is-owner="false" />
        </el-tab-pane>

        <el-tab-pane label="个人信息" name="profile">
          <div class="tab-pane-container">
            <el-descriptions :column="1" border>
              <el-descriptions-item label="用户名">{{ userProfile?.username }}</el-descriptions-item>
              <el-descriptions-item label="真实姓名">{{ userProfile?.realName || '-' }}</el-descriptions-item>
              <el-descriptions-item label="性别">{{ formatGender(userProfile?.gender) }}</el-descriptions-item>
              <el-descriptions-item label="生日">{{
                  userProfile?.birthday ? formatDate(userProfile.birthday) : '-'
                }}
              </el-descriptions-item>
              <el-descriptions-item label="手机号">{{ userProfile?.phone || '-' }}</el-descriptions-item>
              <el-descriptions-item label="邮箱">{{ userProfile?.email || '-' }}</el-descriptions-item>
            </el-descriptions>
          </div>
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <el-dialog v-model="showFollowingDialog" title="关注列表" width="600px" destroy-on-close>
      <UserList :users="followingUsers" @close="showFollowingDialog = false"/>
    </el-dialog>

    <el-dialog v-model="showFollowerDialog" title="粉丝列表" width="600px" destroy-on-close>
      <UserList :users="followerUsers" @close="showFollowerDialog = false"/>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted} from 'vue'
import { useRoute, useRouter} from 'vue-router'
import { ElMessage} from 'element-plus'
import { Star, View, ChatLineRound, ChatDotRound } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
import * as userProfileApi from '@/api/user/userProfile.ts'
import * as userFollowApi from '@/api/user/userFollow.ts'
import * as userMessageApi from '@/api/user/userMessage.ts'
import * as postApi from '@/api/post/post.ts'
import { getAvatarUrl } from '@/utils/file'
import type { UserProfileVO } from '@/models/vo/user/UserProfileVO.ts'
import type { PostVO} from '@/models/vo/post/PostVO.ts'
import UserList from '../../components/user/UserList.vue'
import UserCollectList from '@/components/user/UserCollectList.vue'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()
const userId = ref(Number(route.params.userId))

// UI 控制
const activeTab = ref('posts')
const isFollowing = ref(false)
const followLoading = ref(false)
const showFollowButton = ref(false)
const showFollowingDialog = ref(false)
const showFollowerDialog = ref(false)
const canChat = ref(false)

// 数据定义
const userProfile = ref<UserProfileVO | null>(null)
const userStats = ref({followingCount: 0, followerCount: 0})
const posts = ref<PostVO[]>([])
const postCount = ref(0)
const totalPosts = ref(0)
const currentPage = ref(1)
const pageSize = ref(10)

const followingUsers = ref<UserProfileVO[]>([])
const followerUsers = ref<UserProfileVO[]>([])

/* --- 数据加载逻辑 --- */
const loadUserProfile = async () => {
  try {
    const response = await userProfileApi.getUserProfileByUserId(userId.value)
    if (response.code === 200) {
      userProfile.value = response.data
      await loadUserStats()
      await checkFollowingStatus()
      await loadUserPosts()
    } else {
      ElMessage.error('用户不存在');
      router.push('/404')
    }
  } catch (error) {
    ElMessage.error('加载用户信息失败');
    router.push('/404')
  }
}

const loadUserStats = async () => {
  const response = await userFollowApi.getUserFollowStats(userId.value)
  if (response.code === 200) userStats.value = response.data
}

const checkFollowingStatus = async () => {
  // 如果查看的是自己的资料，不显示关注按钮
  if (userStore.userInfo?.id === userId.value) {
    showFollowButton.value = false
    return
  }

  const response = await userFollowApi.isFollowing(userId.value)
  if (response.code === 200) {
    isFollowing.value = response.data
    showFollowButton.value = true
  }

  // 检查是否可以聊天（互相关注）
  const chatResponse = await userMessageApi.canChatWith(userId.value)
  if (chatResponse.code === 200) {
    canChat.value = chatResponse.data
  }
}

const loadUserPosts = async () => {
  const response = await postApi.listPublishedPostsByUserId(userId.value, currentPage.value, pageSize.value)
  if (response.code === 200) {
    posts.value = response.data.rows
    totalPosts.value = response.data.total
    postCount.value = response.data.total
  }
}

// 事件处理

const toggleFollow = async () => {
  followLoading.value = true
  try {
    const response = isFollowing.value
        ? await userFollowApi.unfollowUser(userId.value)
        : await userFollowApi.followUser(userId.value)

    if (response.code === 200) {
      isFollowing.value = !isFollowing.value
      ElMessage.success(isFollowing.value ? '关注成功' : '已取消关注')
      await loadUserStats()
    }
  } finally {
    followLoading.value = false
  }
}

const showFollowingList = async () => {
  const response = await userFollowApi.listFollowingUsers(userId.value, 1, 50)
  if (response.code === 200) {
    followingUsers.value = response.data.rows
    showFollowingDialog.value = true
  }
}

const showFollowerList = async () => {
  const response = await userFollowApi.listFollowerUsers(userId.value, 1, 50)
  if (response.code === 200) {
    followerUsers.value = response.data.rows
    showFollowerDialog.value = true
  }
}

const startChat = () => {
  router.push({
    name: 'Chat',
    params: { userId: userId.value.toString() },
    query: { name: userProfile.value?.username || '' }
  })
}

const formatGender = (g?: string) => g === 'MALE' ? '男' : (g === 'FEMALE' ? '女' : '-')
const formatDate = (d?: string) => d ? new Date(d).toLocaleDateString('zh-CN') : ''
const goToPostDetail = (id: number) => router.push(`/post/${id}`)
const handleSizeChange = (s: number) => {
  pageSize.value = s;
  loadUserPosts()
}
const handleCurrentChange = (p: number) => {
  currentPage.value = p;
  loadUserPosts()
}

onMounted(() => loadUserProfile())
</script>

<style scoped>
.user-profile-public {
  max-width: 1000px;
  margin: 20px auto;
  padding: 0 20px;
}

.profile-header {
  border-radius: 12px;
  margin-bottom: 20px;
}

.profile-main {
  display: flex;
  align-items: center;
  padding: 20px;
}

.profile-avatar {
  margin-right: 30px;
}

.profile-info {
  flex: 1;
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.profile-username {
  margin: 0 0 15px 0;
  font-size: 24px;
  color: #303133;
}

.profile-stats {
  display: flex;
  gap: 30px;
}

.stat-item {
  text-align: center;
  cursor: pointer;
  padding: 8px;
  border-radius: 6px;
}

.stat-item:hover {
  background-color: #f5f7fa;
}

.stat-number {
  display: block;
  font-weight: bold;
  font-size: 20px;
  color: #303133;
}

.stat-label {
  font-size: 14px;
  color: #909399;
}

.profile-content {
  border-radius: 12px;
}

.tab-pane-container {
  padding: 20px 0;
}

.posts-grid, .collects-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
}

.post-card {
  cursor: pointer;
  transition: all 0.2s;
}

.post-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.post-title {
  margin: 0 0 10px 0;
  font-size: 18px;
  color: #303133;
  line-height: 1.4;
}

.post-meta {
  display: flex;
  justify-content: space-between;
  color: #909399;
  font-size: 14px;
}

.post-stats {
  display: flex;
  gap: 15px;
}

.pagination-wrapper {
  margin-top: 20px;
  display: flex;
  justify-content: center;
}
</style>

// frontend/src/pages/profile/UserProfilePublic.tsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Card,
  Avatar,
  Button,
  Tabs,
  Empty,
  Pagination,
  Tag,
  Descriptions,
  Modal,
  Message,
} from '@arco-design/web-react';
import {
  IconStar,
  IconEye,
  IconMessage,
  IconUser,
} from '@arco-design/web-react/icon';
import { useUserStore } from '@/stores/user';
import * as userProfileApi from '@/api/user/userProfile.ts';
import * as userFollowApi from '@/api/user/userFollow.ts';
import * as userMessageApi from '@/api/user/userMessage.ts';
import * as postApi from '@/api/post/post.ts';
import { getAvatarUrl } from '@/utils/file';
import type { UserProfileVO } from '@/models/vo/user';
import type { PostVO } from '@/models/vo/post';
import UserList from '@/components/user/UserList';
import UserCollectList from '@/components/user/UserCollectList';
import './UserProfilePublic.css';

const UserProfilePublic: React.FC = () => {
  const { userId } = useParams<{ userId: string }>();
  const navigate = useNavigate();
  const userStore = useUserStore();

  const userIdNum = Number(userId);

  // UI control
  const [activeTab, setActiveTab] = useState('posts');
  const [isFollowing, setIsFollowing] = useState(false);
  const [followLoading, setFollowLoading] = useState(false);
  const [showFollowButton, setShowFollowButton] = useState(false);
  const [showFollowingDialog, setShowFollowingDialog] = useState(false);
  const [showFollowerDialog, setShowFollowerDialog] = useState(false);
  const [canChat, setCanChat] = useState(false);

  // Data
  const [userProfile, setUserProfile] = useState<UserProfileVO | null>(null);
  const [userStats, setUserStats] = useState({
    followingCount: 0,
    followerCount: 0,
  });
  const [posts, setPosts] = useState<PostVO[]>([]);
  const [postCount, setPostCount] = useState(0);
  const [totalPosts, setTotalPosts] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const [followingUsers, setFollowingUsers] = useState<UserProfileVO[]>([]);
  const [followerUsers, setFollowerUsers] = useState<UserProfileVO[]>([]);

  /* --- Data loading --- */
  const loadUserStats = async () => {
    const response = await userFollowApi.getUserFollowStats(userIdNum);
    if (response.code === 200) setUserStats(response.data);
  };

  const checkFollowingStatus = async () => {
    // Don't show follow button if viewing own profile
    if (userStore.userInfo?.id === userIdNum) {
      setShowFollowButton(false);
      return;
    }

    const response = await userFollowApi.isFollowing(userIdNum);
    if (response.code === 200) {
      setIsFollowing(response.data);
      setShowFollowButton(true);
    }

    // Check if can chat (mutual follow)
    const chatResponse = await userMessageApi.canChatWith(userIdNum);
    if (chatResponse.code === 200) {
      setCanChat(chatResponse.data);
    }
  };

  const loadUserPosts = async () => {
    const response = await postApi.listPublishedPostsByUserId(
      userIdNum,
      currentPage,
      pageSize
    );
    if (response.code === 200) {
      setPosts(response.data.rows);
      setTotalPosts(response.data.total);
      setPostCount(response.data.total);
    }
  };

  const loadUserProfile = async () => {
    try {
      const response = await userProfileApi.getUserProfileByUserId(userIdNum);
      if (response.code === 200) {
        setUserProfile(response.data);
        await loadUserStats();
        await checkFollowingStatus();
        await loadUserPosts();
      } else {
        Message.error('用户不存在');
        navigate('/404');
      }
    } catch {
      Message.error('加载用户信息失败');
      navigate('/404');
    }
  };

  useEffect(() => {
    loadUserProfile();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userIdNum]);

  // Reload posts when page changes
  useEffect(() => {
    if (userProfile) {
      loadUserPosts();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentPage, pageSize]);

  // Event handlers
  const toggleFollow = async () => {
    setFollowLoading(true);
    try {
      const response = isFollowing
        ? await userFollowApi.unfollowUser(userIdNum)
        : await userFollowApi.followUser(userIdNum);

      if (response.code === 200) {
        setIsFollowing(!isFollowing);
        Message.success(isFollowing ? '已取消关注' : '关注成功');
        await loadUserStats();
      }
    } finally {
      setFollowLoading(false);
    }
  };

  const showFollowingList = async () => {
    const response = await userFollowApi.listFollowingUsers(userIdNum, 1, 50);
    if (response.code === 200) {
      setFollowingUsers(response.data.rows);
      setShowFollowingDialog(true);
    }
  };

  const showFollowerList = async () => {
    const response = await userFollowApi.listFollowerUsers(userIdNum, 1, 50);
    if (response.code === 200) {
      setFollowerUsers(response.data.rows);
      setShowFollowerDialog(true);
    }
  };

  const startChat = () => {
    navigate(`/chat/${userIdNum}?name=${userProfile?.username || ''}`);
  };

  const formatGender = (g?: string) =>
    g === 'MALE' ? '男' : g === 'FEMALE' ? '女' : '-';

  const formatDate = (d?: string) =>
    d ? new Date(d).toLocaleDateString('zh-CN') : '';

  const goToPostDetail = (id: number) => navigate(`/post/${id}`);

  const handleSizeChange = (size: number) => {
    setPageSize(size);
    setCurrentPage(1);
  };

  const handleCurrentChange = (page: number) => {
    setCurrentPage(page);
  };

  return (
    <div className="user-profile-public">
      <Card className="profile-header">
        <div className="profile-main">
          <div className="profile-avatar">
            <Avatar size={120}>
              <img src={getAvatarUrl(userProfile?.avatar)} alt="" />
              {userProfile?.username?.charAt(0).toUpperCase()}
            </Avatar>
          </div>
          <div className="profile-info">
            <div className="profile-basic">
              <h2 className="profile-username">{userProfile?.username}</h2>
              <div className="profile-stats">
                <div className="stat-item" onClick={showFollowingList}>
                  <span className="stat-number">
                    {userStats.followingCount}
                  </span>
                  <span className="stat-label">关注</span>
                </div>
                <div className="stat-item" onClick={showFollowerList}>
                  <span className="stat-number">
                    {userStats.followerCount}
                  </span>
                  <span className="stat-label">粉丝</span>
                </div>
                <div className="stat-item">
                  <span className="stat-number">{postCount}</span>
                  <span className="stat-label">文章</span>
                </div>
              </div>
            </div>
            <div className="profile-actions">
              {showFollowButton && (
                <Button
                  type={isFollowing ? 'secondary' : 'primary'}
                  icon={<IconStar />}
                  onClick={toggleFollow}
                  loading={followLoading}
                  size="large"
                >
                  {isFollowing ? '取消关注' : '关注'}
                </Button>
              )}
              {canChat && (
                <Button
                  type="primary"
                  status="success"
                  icon={<IconUser />}
                  onClick={startChat}
                  size="large"
                >
                  发消息
                </Button>
              )}
            </div>
          </div>
        </div>
      </Card>

      <Card className="profile-content">
        <Tabs activeTab={activeTab} onChange={setActiveTab} className="profile-tabs">
          <Tabs.TabPane key="posts" title="文章">
            <div className="tab-pane-container">
              {posts.length === 0 ? (
                <Empty description="暂无文章" />
              ) : (
                <div className="posts-grid">
                  {posts.map((post) => (
                    <Card
                      key={post.id}
                      className="post-card"
                      hoverable
                      onClick={() => goToPostDetail(post.id)}
                    >
                      <h3 className="post-title">{post.title}</h3>
                      <div className="post-meta">
                        <span className="post-date">
                          {formatDate(post.createdAt)}
                        </span>
                        <span className="post-stats">
                          <IconEye /> {post.viewCount || 0}
                          <IconMessage /> {post.commentCount || 0}
                          <IconStar /> {post.likeCount || 0}
                        </span>
                      </div>
                      {post.tags && post.tags.length > 0 && (
                        <div className="post-tags">
                          {post.tags.map((tag) => (
                            <Tag key={tag} size="small" color="gray" className="tag">
                              {tag}
                            </Tag>
                          ))}
                        </div>
                      )}
                    </Card>
                  ))}
                </div>
              )}

              {totalPosts > pageSize && (
                <div className="pagination-wrapper">
                  <Pagination
                    current={currentPage}
                    pageSize={pageSize}
                    total={totalPosts}
                    sizeOptions={[10, 20, 50]}
                    showTotal
                    showJumper
                    
                    onChange={handleCurrentChange}
                    onPageSizeChange={handleSizeChange}
                  />
                </div>
              )}
            </div>
          </Tabs.TabPane>

          <Tabs.TabPane key="collects" title="收藏">
            <UserCollectList userId={userIdNum} isOwner={false} />
          </Tabs.TabPane>

          <Tabs.TabPane key="profile" title="个人信息">
            <div className="tab-pane-container">
              <Descriptions
                column={1}
                border
                labelStyle={{ width: 100 }}
                data={[
                  {
                    label: '用户名',
                    value: userProfile?.username || '-',
                  },
                  {
                    label: '真实姓名',
                    value: userProfile?.realName || '-',
                  },
                  {
                    label: '性别',
                    value: formatGender(userProfile?.gender),
                  },
                  {
                    label: '生日',
                    value: userProfile?.birthday
                      ? formatDate(userProfile.birthday)
                      : '-',
                  },
                  {
                    label: '手机号',
                    value: userProfile?.phone || '-',
                  },
                  {
                    label: '邮箱',
                    value: userProfile?.email || '-',
                  },
                ]}
              />
            </div>
          </Tabs.TabPane>
        </Tabs>
      </Card>

      <Modal
        title="关注列表"
        visible={showFollowingDialog}
        onCancel={() => setShowFollowingDialog(false)}
        footer={null}
      >
        <UserList
          users={followingUsers}
          onClose={() => setShowFollowingDialog(false)}
        />
      </Modal>

      <Modal
        title="粉丝列表"
        visible={showFollowerDialog}
        onCancel={() => setShowFollowerDialog(false)}
        footer={null}
      >
        <UserList
          users={followerUsers}
          onClose={() => setShowFollowerDialog(false)}
        />
      </Modal>
    </div>
  );
};

export default UserProfilePublic;
