// ui-vue/src/views/auth/Register.vue
<template>
  <div class="register-container">
    <div class="register-card">
      <div class="register-header">
        <div class="register-title">用户注册</div>
        <div class="register-subtitle">创建您的账户</div>
      </div>

      <el-form
        ref="formRef"
        :model="registerForm"
        :rules="registerRules"
        class="register-form"
        size="large"
      >
        <el-form-item prop="username">
          <el-input
            v-model="registerForm.username"
            placeholder="请输入用户名"
            :prefix-icon="User"
            clearable
          />
        </el-form-item>

        <el-form-item prop="password">
          <el-input
            v-model="registerForm.password"
            type="password"
            placeholder="请输入密码"
            :prefix-icon="Lock"
            show-password
            clearable
          />
        </el-form-item>

        <el-form-item prop="confirmPassword">
          <el-input
            v-model="registerForm.confirmPassword"
            type="password"
            placeholder="请确认密码"
            :prefix-icon="Lock"
            show-password
            clearable
          />
        </el-form-item>

        <el-form-item prop="phone">
          <el-input
            v-model="registerForm.phone"
            placeholder="请输入手机号码（可选）"
            :prefix-icon="Phone"
            clearable
          />
        </el-form-item>

        <el-form-item prop="email">
          <el-input
            v-model="registerForm.email"
            placeholder="请输入邮箱地址（可选）"
            :prefix-icon="Message"
            clearable
          />
        </el-form-item>

        <el-form-item>
          <el-button
            type="primary"
            size="large"
            :loading="loading"
            class="register-button"
            @click="handleRegister"
          >
            注册
          </el-button>
        </el-form-item>
      </el-form>

      <div class="register-footer">
        <span>已有账号？</span>
        <el-link type="primary" :underline="false" @click="$router.push('/login')">
          立即登录
        </el-link>
      </div>
    </div>

    <div class="register-background">
      <div class="background-circle circle1"></div>
      <div class="background-circle circle2"></div>
      <div class="background-circle circle3"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { User, Lock, Phone, Message } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'

const router = useRouter()
const userStore = useUserStore()
const formRef = ref()
const loading = ref(false)

const registerForm = reactive({
  username: '',
  password: '',
  confirmPassword: '',
  phone: '',
  email: ''
})

const validateConfirmPassword = (rule: any, value: string, callback: Function) => {
  if (value !== registerForm.password) {
    callback(new Error('两次输入的密码不一致'))
  } else {
    callback()
  }
}

const registerRules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { min: 2, max: 20, message: '用户名长度应在2-20个字符之间', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码至少6位', trigger: 'blur' }
  ],
  confirmPassword: [
    { required: true, message: '请确认密码', trigger: 'blur' },
    { validator: validateConfirmPassword, trigger: 'blur' }
  ],
  phone: [
    {
      pattern: /^1[3-9]\d{9}$/,
      message: '电话号码格式不正确',
      trigger: 'blur'
    }
  ],
  email: [
    {
      type: 'email',
      message: '邮箱格式不正确',
      trigger: 'blur'
    }
  ]
}

const handleRegister = async () => {
  if (!formRef.value) return

  await formRef.value.validate(async (valid: boolean) => {
    if (!valid) return

    loading.value = true
    try {
      const result = await userStore.register({
        username: registerForm.username,
        password: registerForm.password,
        phone: registerForm.phone || undefined,
        email: registerForm.email || undefined
      })

      if (result.success) {
        ElMessage.success('注册成功！正在跳转到登录页面...')
        setTimeout(() => {
          router.push('/login')
        }, 1500)
      } else {
        ElMessage.error(result.message || '注册失败')
      }
    } catch (error) {
      ElMessage.error('注册失败，请稍后重试')
      console.error('Register error:', error)
    } finally {
      loading.value = false
    }
  })
}
</script>

<style scoped>
.register-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  overflow: hidden;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.register-background {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
  z-index: 1;
  pointer-events: none;
}

.background-circle {
  position: absolute;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.1);
  animation: float 20s infinite linear;
  pointer-events: none;
}

.circle1 {
  width: 300px;
  height: 300px;
  top: -150px;
  right: -150px;
}

.circle2 {
  width: 200px;
  height: 200px;
  bottom: -100px;
  left: -100px;
  animation-delay: -10s;
}

.circle3 {
  width: 150px;
  height: 150px;
  top: 20%;
  left: 10%;
  animation-delay: -15s;
}

@keyframes float {
  0% {
    transform: translate(0, 0) rotate(0deg);
  }
  25% {
    transform: translate(-20px, 20px) rotate(90deg);
  }
  50% {
    transform: translate(0, 40px) rotate(180deg);
  }
  75% {
    transform: translate(20px, 20px) rotate(270deg);
  }
  100% {
    transform: translate(0, 0) rotate(360deg);
  }
}

.register-card {
  position: relative;
  z-index: 10;
  width: 480px;
  padding: 40px;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 20px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
  backdrop-filter: blur(10px);
}

.register-header {
  text-align: center;
  margin-bottom: 30px;
}

.register-title {
  font-size: 32px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 8px;
}

.register-subtitle {
  font-size: 14px;
  color: #909399;
}

.register-form {
  margin-bottom: 20px;
}

.register-button {
  width: 100%;
  height: 44px;
  font-size: 16px;
  font-weight: 500;
  border-radius: 8px;
}

.register-footer {
  text-align: center;
  font-size: 14px;
  color: #909399;
  padding-top: 20px;
  border-top: 1px solid #e4e7ed;
}

:deep(.el-input__wrapper) {
  border-radius: 8px;
  box-shadow: none;
  border: 1px solid #dcdfe6;
  transition: all 0.3s;
}

:deep(.el-input__wrapper:hover) {
  border-color: #409eff;
}

:deep(.el-input__wrapper.is-focus) {
  border-color: #409eff;
  box-shadow: 0 0 0 2px rgba(64, 158, 255, 0.1);
}

:deep(.el-form-item.is-error .el-input__wrapper) {
  border-color: #f56c6c;
}
</style>

// frontend/src/pages/auth/Register.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Form, Input, Button, Message, Link } from '@arco-design/web-react'
import { IconUser, IconLock, IconPhone, IconEmail } from '@arco-design/web-react/icon'
import { useUserStore } from '@/stores/user'
import type { RegisterRequest } from '@/models/request/auth'

import './Register.css'

const Register = () => {
  const navigate = useNavigate()
  const userStore = useUserStore()
  const [formRef] = Form.useForm()
  const [loading, setLoading] = useState(false)

  const [registerForm, setRegisterForm] = useState<Omit<RegisterRequest, 'phone' | 'email'> & { phone: string; email: string; confirmPassword: string }>({
    username: '',
    password: '',
    confirmPassword: '',
    phone: '',
    email: ''
  })

  const updateField = (field: string, value: string) => {
    setRegisterForm((prev) => ({ ...prev, [field]: value }))
  }

  const validateConfirmPassword = (value: string | undefined, callback: (error?: string) => void) => {
    if (value !== registerForm.password) {
      callback('两次输入的密码不一致')
    } else {
      callback()
    }
  }

  const handleRegister = async () => {
    try {
      await formRef.validate()
    } catch {
      return
    }

    setLoading(true)
    try {
      const result = await userStore.register({
        username: registerForm.username,
        password: registerForm.password,
        phone: registerForm.phone || undefined,
        email: registerForm.email || undefined
      })

      if (result.success) {
        Message.success('注册成功！正在跳转到登录页面...')
        setTimeout(() => {
          navigate('/login')
        }, 1500)
      } else {
        Message.error(result.message || '注册失败')
      }
    } catch {
      Message.error('注册失败，请稍后重试')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="register-container">
      <div className="register-card">
        <div className="register-header">
          <div className="register-title">用户注册</div>
          <div className="register-subtitle">创建您的账户</div>
        </div>

        <Form
          form={formRef}
          className="register-form"
          size="large"
          onSubmit={handleRegister}
        >
          <Form.Item
            field="username"
            rules={[
              { required: true, message: '请输入用户名' },
              { minLength: 2, maxLength: 20, message: '用户名长度应在2-20个字符之间' }
            ]}
          >
            <Input
              value={registerForm.username}
              onChange={(value) => updateField('username', value)}
              placeholder="请输入用户名"
              prefix={<IconUser />}
              allowClear
            />
          </Form.Item>

          <Form.Item
            field="password"
            rules={[
              { required: true, message: '请输入密码' },
              { minLength: 6, message: '密码至少6位' }
            ]}
          >
            <Input.Password
              value={registerForm.password}
              onChange={(value) => updateField('password', value)}
              placeholder="请输入密码"
              prefix={<IconLock />}
            />
          </Form.Item>

          <Form.Item
            field="confirmPassword"
            rules={[
              { required: true, message: '请确认密码' },
              { validator: validateConfirmPassword }
            ]}
          >
            <Input.Password
              value={registerForm.confirmPassword}
              onChange={(value) => updateField('confirmPassword', value)}
              placeholder="请确认密码"
              prefix={<IconLock />}
            />
          </Form.Item>

          <Form.Item
            field="phone"
            rules={[
              { match: /^1[3-9]\d{9}$/, message: '电话号码格式不正确' }
            ]}
          >
            <Input
              value={registerForm.phone}
              onChange={(value) => updateField('phone', value)}
              placeholder="请输入手机号码（可选）"
              prefix={<IconPhone />}
              allowClear
            />
          </Form.Item>

          <Form.Item
            field="email"
            rules={[
              { type: 'email', message: '邮箱格式不正确' }
            ]}
          >
            <Input
              value={registerForm.email}
              onChange={(value) => updateField('email', value)}
              placeholder="请输入邮箱地址（可选）"
              prefix={<IconEmail />}
              allowClear
            />
          </Form.Item>

          <Form.Item>
            <Button
              type="primary"
              size="large"
              loading={loading}
              className="register-button"
              onClick={handleRegister}
            >
              注册
            </Button>
          </Form.Item>
        </Form>

        <div className="register-footer">
          <span>已有账号？</span>
          <Link type="primary" onClick={() => navigate('/login')}>
            立即登录
          </Link>
        </div>
      </div>

      <div className="register-background">
        <div className="background-circle circle1"></div>
        <div className="background-circle circle2"></div>
        <div className="background-circle circle3"></div>
      </div>
    </div>
  )
}

export default Register
