// ui-vue/src/components/post/CommentList.vue
<template>
  <div class="comment-list-container">
    <div class="comment-tabs">
      <el-radio-group v-model="activeTab" size="small" @change="handleTabChange">
        <el-radio-button label="all">全部评论 ({{ totalCount }})</el-radio-button>
        <el-radio-button label="hot">热评</el-radio-button>
        <el-radio-button label="latest">最新</el-radio-button>
      </el-radio-group>
    </div>

    <div v-loading="loading" class="comments-content">
      <div v-if="comments.length === 0 && !loading" class="empty-state">
        <el-empty description="暂无评论，快来抢沙发吧~" />
      </div>

      <CommentItem
          v-for="comment in comments"
          :key="comment.id"
          :comment="comment"
          @reply="handleReply"
          @like="handleLike"
          @delete="handleDelete"
      />

      <div v-if="hasMore && !loading" class="load-more">
        <el-button text @click="loadMore">
          加载更多评论
        </el-button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { ElMessage } from 'element-plus'
import CommentItem from './CommentItem.vue'
import { commentApi } from '@/api/postComment.ts'
import type { CommentVO } from '@/models/vo/post/CommentVO'

interface Props {
  postId: number
  pageSize?: number
}

interface Emits {
  (e: 'update:total', count: number): void
}

const props = withDefaults(defineProps<Props>(), {
  pageSize: 10
})

const emit = defineEmits<Emits>()

const activeTab = ref<'all' | 'hot' | 'latest'>('all')
const loading = ref(false)
const comments = ref<CommentVO[]>([])
const totalCount = ref(0)
const currentPage = ref(1)
const hasMore = ref(false)

const loadComments = async (reset = true) => {
  if (loading.value) return

  loading.value = true
  try {
    let response

    if (activeTab.value === 'all') {
      response = await commentApi.getCommentTree(props.postId)
      if (response.code === 200) {
        comments.value = response.data || []
        totalCount.value = comments.value.length
        hasMore.value = false
      }
    } else if (activeTab.value === 'hot') {
      response = await commentApi.listHotComments(props.postId, props.pageSize)
      if (response.code === 200) {
        comments.value = response.data || []
        totalCount.value = comments.value.length
        hasMore.value = false
      }
    } else if (activeTab.value === 'latest') {
      response = await commentApi.listLatestComments(props.postId, props.pageSize)
      if (response.code === 200) {
        comments.value = response.data || []
        totalCount.value = comments.value.length
        hasMore.value = false
      }
    }

    emit('update:total', totalCount.value)
  } catch (error) {
    console.error('加载评论失败:', error)
    ElMessage.error('加载评论失败')
  } finally {
    loading.value = false
  }
}

const loadMore = () => {
  // 评论树模式下不需要加载更多
}

const handleTabChange = () => {
  loadComments(true)
}

const handleReply = (commentId: number) => {
  console.log('Reply to comment:', commentId)
}

const handleLike = (commentId: number) => {
  console.log('Like comment:', commentId)
}

const handleDelete = (commentId: number) => {
  const index = comments.value.findIndex(c => c.id === commentId)
  if (index !== -1) {
    comments.value.splice(index, 1)
    totalCount.value--
    emit('update:total', totalCount.value)
  }
}

const refresh = () => {
  loadComments(true)
}

watch(() => props.postId, () => {
  if (props.postId) {
    loadComments(true)
  }
})

onMounted(() => {
  if (props.postId) {
    loadComments(true)
  }
})

defineExpose({
  refresh
})
</script>

<style scoped>
.comment-list-container {
  width: 100%;
}

.comment-tabs {
  margin-bottom: 20px;
  padding-bottom: 12px;
  border-bottom: 1px solid #ebeef5;
}

.comments-content {
  min-height: 200px;
}

.empty-state {
  padding: 40px 0;
}

.load-more {
  text-align: center;
  padding: 20px 0;
  margin-top: 20px;
  border-top: 1px solid #ebeef5;
}
</style>

// frontend/src/components/post/CommentList.tsx
import { useState, useEffect, useImperativeHandle, forwardRef } from 'react';
import { Radio, Button, Empty, Spin } from '@arco-design/web-react';
import * as commentApi from '@/api/post/postComment';
import type { CommentVO } from '@/models/vo/post';
import CommentItem from './CommentItem';

interface CommentListProps {
  postId: number;
  pageSize?: number;
  onUpdateTotal?: (count: number) => void;
}

export interface CommentListRef {
  refresh: () => void;
}

const CommentList = forwardRef<CommentListRef, CommentListProps>((props, ref) => {
  const { postId, pageSize = 10, onUpdateTotal } = props;

  const [activeTab, setActiveTab] = useState<'all' | 'hot' | 'latest'>('all');
  const [loading, setLoading] = useState(false);
  const [comments, setComments] = useState<CommentVO[]>([]);
  const [totalCount, setTotalCount] = useState(0);
  const [hasMore, setHasMore] = useState(false);

  const loadComments = async (_reset = true) => {
    if (loading) return;

    setLoading(true);
    try {
      let response;
      let count = 0;

      if (activeTab === 'all') {
        response = await commentApi.getCommentTree(postId);
        if (response.code === 200) {
          const data = response.data || [];
          setComments(data);
          count = data.length;
          setTotalCount(count);
          setHasMore(false);
        }
      } else if (activeTab === 'hot') {
        response = await commentApi.listHotComments(postId, pageSize);
        if (response.code === 200) {
          const data = response.data || [];
          setComments(data);
          count = data.length;
          setTotalCount(count);
          setHasMore(false);
        }
      } else if (activeTab === 'latest') {
        response = await commentApi.listLatestComments(postId, pageSize);
        if (response.code === 200) {
          const data = response.data || [];
          setComments(data);
          count = data.length;
          setTotalCount(count);
          setHasMore(false);
        }
      }

      onUpdateTotal?.(count);
    } catch (error) {
      console.error('加载评论失败:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (postId) {
      loadComments(true);
    }
  }, [postId, activeTab]);

  useImperativeHandle(ref, () => ({
    refresh: () => {
      loadComments(true);
    },
  }));

  const handleTabChange = (value: string) => {
    setActiveTab(value as 'all' | 'hot' | 'latest');
  };

  return (
    <div className="comment-list-container">
      <div className="comment-tabs">
        <Radio.Group type="button" value={activeTab} onChange={handleTabChange}>
          <Radio value="all">全部评论 ({totalCount})</Radio>
          <Radio value="hot">热评</Radio>
          <Radio value="latest">最新</Radio>
        </Radio.Group>
      </div>

      <Spin loading={loading} className="comments-content">
        {comments.length === 0 && !loading ? (
          <Empty description="暂无评论，快来抢沙发吧~" />
        ) : (
          comments.map((comment) => (
            <CommentItem
              key={comment.id}
              comment={comment}
              onReply={(_commentId) => {
                // Handle reply - could emit to parent via a callback prop
              }}
              onLike={async (commentId) => {
                try {
                  const res = await commentApi.likeComment(commentId);
                  if (res.code === 200) {
                    loadComments();
                  }
                } catch (error) {
                  console.error('点赞失败:', error);
                }
              }}
              onDelete={async (commentId) => {
                try {
                  const res = await commentApi.deleteComment(commentId);
                  if (res.code === 200) {
                    loadComments();
                  }
                } catch (error) {
                  console.error('删除评论失败:', error);
                }
              }}
            />
          ))
        )}

        {hasMore && !loading && (
          <div className="load-more">
            <Button type="text" onClick={() => {}}>
              加载更多评论
            </Button>
          </div>
        )}
      </Spin>
    </div>
  );
});

export default CommentList;
