// ui-vue/src/layouts/AdminLayout.vue
<template>
  <div class="admin-layout">
    <el-container class="layout-container">
      <el-aside width="240px" class="layout-aside">
        <div class="aside-header">
          <div class="logo">
            <el-icon :size="24"><Platform /></el-icon>
            <span class="logo-text">用户管理系统</span>
          </div>
        </div>

        <el-menu
          router
          :default-active="activeMenu"
          class="aside-menu"
          background-color="#304156"
          text-color="#bfcbd9"
          active-text-color="#409eff"
        >
          <el-menu-item index="/">
            <el-icon><House /></el-icon>
            <span>返回首页</span>
          </el-menu-item>
          <el-menu-item index="/admin/users">
            <el-icon><User /></el-icon>
            <span>用户管理</span>
          </el-menu-item>
          <el-sub-menu index="posts">
            <template #title>
              <el-icon><Document /></el-icon>
              <span>内容管理</span>
            </template>
            <el-menu-item index="/admin/posts">博文管理</el-menu-item>
            <el-menu-item index="/admin/audit">博文审核</el-menu-item>
            <el-menu-item index="/admin/post-monitor">博文数据监控</el-menu-item>
          </el-sub-menu>
          <el-menu-item index="/admin/profile">
            <el-icon><Avatar /></el-icon>
            <span>个人中心</span>
          </el-menu-item>
          <el-menu-item index="/admin/logs">
            <el-icon><Document /></el-icon>
            <span>系统日志</span>
          </el-menu-item>
          <el-menu-item index="/admin/settings">
            <el-icon><Setting /></el-icon>
            <span>系统设置</span>
          </el-menu-item>
        </el-menu>
      </el-aside>

      <el-container class="layout-main">
        <el-header class="layout-header">
          <div class="header-left">
            <el-breadcrumb separator="/">
              <el-breadcrumb-item
                v-for="item in breadcrumbs"
                :key="item.path"
                :to="{ path: item.path }"
              >
                {{ item.meta?.title }}
              </el-breadcrumb-item>
            </el-breadcrumb>
          </div>

          <div class="header-right">
            <el-dropdown trigger="hover" @command="handleCommand">
              <div class="user-info">
                <el-avatar :size="32" :src="getAvatarUrl(userStore.userProfile?.avatar)">
                  {{ userStore.userInfo?.username?.charAt(0).toUpperCase() }}
                </el-avatar>
                <span class="username">{{ userStore.userInfo?.username }}</span>
                <el-icon class="el-icon--right"><arrow-down /></el-icon>
              </div>
              <template #dropdown>
                <el-dropdown-menu>
                  <el-dropdown-item command="profile">
                    <el-icon><User /></el-icon>
                    个人中心
                  </el-dropdown-item>
                  <el-dropdown-item divided command="logout">
                    <el-icon><SwitchButton /></el-icon>
                    退出登录
                  </el-dropdown-item>
                </el-dropdown-menu>
              </template>
            </el-dropdown>
          </div>
        </el-header>

        <el-main class="layout-content">
          <router-view />
        </el-main>
      </el-container>
    </el-container>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  Platform,
  User,
  Avatar,
  Setting,
  ArrowDown,
  SwitchButton,
  Document,
  House
} from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
import { getAvatarUrl } from '@/utils/file'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()

const activeMenu = computed(() => route.path)
const breadcrumbs = computed(() => route.matched.filter(item => item.meta?.title))

const handleCommand = async (command: string) => {
  switch (command) {
    case 'profile':
      router.push('/admin/profile')
      break
    case 'logout':
      try {
        await ElMessageBox.confirm('确定要退出登录吗？', '提示', {
          type: 'warning'
        })
        await userStore.logout()
        router.push('/login')
        ElMessage.success('已退出登录')
      } catch {
        // 取消退出
      }
      break
  }
}
</script>

<style scoped>
.admin-layout {
  height: 100vh;
}

.layout-container {
  height: 100%;
}

.layout-aside {
  background-color: #304156;
  box-shadow: 2px 0 8px rgba(0, 0, 0, 0.1);
  transition: width 0.3s;
}

.aside-header {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 60px;
  border-bottom: 1px solid #2a3a4a;
}

.logo {
  display: flex;
  align-items: center;
  gap: 12px;
  color: #fff;
}

.logo-text {
  font-size: 18px;
  font-weight: 600;
  color: #fff;
}

.aside-menu {
  border-right: none;
}

.layout-main {
  background-color: #f0f2f5;
}

.layout-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  background-color: #fff;
  box-shadow: 0 1px 4px rgba(0, 21, 41, 0.08);
  height: 60px;
}

.header-right .user-info {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  padding: 8px 12px;
  border-radius: 20px;
  transition: all 0.3s;
}

.header-right .user-info:hover {
  background-color: #f5f7fa;
}

.username {
  font-size: 14px;
  color: #606266;
  font-weight: 500;
}

.layout-content {
  padding: 24px;
}

:deep(.el-menu-item.is-active) {
  background-color: #263445 !important;
}

:deep(.el-menu-item:hover) {
  background-color: #263445 !important;
}

:deep(.el-sub-menu__title:hover) {
  background-color: #263445 !important;
}
</style>

// frontend/src/layouts/AdminLayout.tsx
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { Layout, Menu, Avatar, Dropdown, Breadcrumb, Message, Modal } from '@arco-design/web-react'
import {
  IconApps,
  IconHome,
  IconUser,
  IconFile,
  IconSettings,
  IconExport,
} from '@arco-design/web-react/icon'
import { useUserStore } from '@/stores/user'
import { getAvatarUrl } from '@/utils/file'
import './AdminLayout.css'

const { Sider, Header, Content } = Layout

export default function AdminLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const userStore = useUserStore()
  const isAdmin = userStore.isAdmin

  const handleMenuClick = (key: string) => {
    navigate(key)
  }

  const handleUserCommand = async (command: string) => {
    switch (command) {
      case 'profile':
        navigate('/admin/profile')
        break
      case 'logout':
        Modal.confirm({
          title: '提示',
          content: '确定要退出登录吗？',
          onOk: async () => {
            await userStore.logout()
            navigate('/login')
            Message.success('已退出登录')
          },
        })
        break
    }
  }

  const menuItems = [
    { key: '/', icon: <IconHome />, label: '返回首页' },
    ...(isAdmin ? [{ key: '/admin/users', icon: <IconUser />, label: '用户管理' }] : []),
    { key: '/admin/posts', icon: <IconFile />, label: '博文管理' },
    { key: '/admin/audit', icon: <IconFile />, label: '博文审核' },
    { key: '/admin/post-monitor', icon: <IconFile />, label: '博文数据监控' },
    { key: '/admin/profile', icon: <IconUser />, label: '个人中心' },
    ...(isAdmin ? [{ key: '/admin/logs', icon: <IconFile />, label: '系统日志' }] : []),
    ...(isAdmin ? [{ key: '/admin/settings', icon: <IconSettings />, label: '系统设置' }] : []),
  ]

  const pathLabels: Record<string, string> = {
    admin: '管理后台',
    users: '用户管理',
    posts: '博文管理',
    'post-monitor': '数据监控',
    audit: '博文审核',
    profile: '个人中心',
    logs: '系统日志',
    settings: '系统设置',
  }

  const breadcrumbItems = location.pathname
    .split('/')
    .filter(Boolean)
    .map((segment, index, arr) => {
      const path = '/' + arr.slice(0, index + 1).join('/')
      return { path, label: pathLabels[segment] || segment }
    })

  return (
    <div className="admin-layout">
      <Layout className="layout-container">
        <Sider width={240} className="layout-aside">
          <div className="aside-header">
            <div className="logo">
              <IconApps style={{ fontSize: 24 }} />
              <span className="logo-text">用户管理系统</span>
            </div>
          </div>
          <Menu
            selectedKeys={[location.pathname]}
            onClickMenuItem={handleMenuClick}
            className="aside-menu"
          >
            {menuItems.map((item) => (
              <Menu.Item key={item.key}>
                {item.icon} {item.label}
              </Menu.Item>
            ))}
          </Menu>
        </Sider>

        <Layout className="layout-main">
          <Header className="layout-header">
            <div className="header-left">
              <Breadcrumb>
                {breadcrumbItems.map((item) => (
                  <Breadcrumb.Item key={item.path} onClick={() => navigate(item.path)}>
                    {item.label}
                  </Breadcrumb.Item>
                ))}
              </Breadcrumb>
            </div>

            <div className="header-right">
              <Dropdown
                droplist={
                  <Menu onClickMenuItem={handleUserCommand}>
                    <Menu.Item key="profile">
                      <IconUser /> 个人中心
                    </Menu.Item>
                    <Menu.Item key="logout">
                      <IconExport /> 退出登录
                    </Menu.Item>
                  </Menu>
                }
                trigger="hover"
              >
                <div className="user-info">
                  <Avatar size={32}>
                    <img src={getAvatarUrl(userStore.userProfile?.avatar)} alt="" />
                    {userStore.userInfo?.username?.charAt(0).toUpperCase()}
                  </Avatar>
                  <span className="username">{userStore.userInfo?.username}</span>
                </div>
              </Dropdown>
            </div>
          </Header>

          <Content className="layout-content">
            <Outlet />
          </Content>
        </Layout>
      </Layout>
    </div>
  )
}
