// frontend/src/components/llm/LlmSummaryPostDialog.tsx
import { useState, useImperativeHandle, forwardRef } from 'react';
import { Modal, Button, Alert, Empty, Spin, Message } from '@arco-design/web-react';
import { IconRobot } from '@arco-design/web-react/icon';
import * as llmChatApi from '@/api/llm/llmChat';

interface LlmSummaryPostDialogProps {
  title: string;
  content: string;
}

export interface LlmSummaryPostDialogRef {
  open: () => void;
}

const LlmSummaryPostDialog = forwardRef<LlmSummaryPostDialogRef, LlmSummaryPostDialogProps>(
  (props, ref) => {
    const { title, content } = props;

    const [visible, setVisible] = useState(false);
    const [loading, setLoading] = useState(false);
    const [summary, setSummary] = useState('');
    const [error, setError] = useState('');

    useImperativeHandle(ref, () => ({
      open: () => {
        setVisible(true);
        setError('');
      },
    }));

    const handleGenerate = async () => {
      if (!title || !content) {
        Message.warning('文章标题或内容为空');
        return;
      }

      setLoading(true);
      setError('');
      setSummary('');

      try {
        const response = await llmChatApi.generatePostSummary(title, content);
        setSummary(response.summary);
        Message.success('AI 摘要生成成功');
      } catch (err) {
        console.error('生成 AI 摘要失败:', err);
        setError('生成摘要失败，请稍后重试');
        Message.error('生成摘要失败');
      } finally {
        setLoading(false);
      }
    };

    const handleClose = () => {
      setVisible(false);
      setSummary('');
      setError('');
    };

    return (
      <Modal
        title="AI 文章摘要"
        visible={visible}
        onCancel={handleClose}
        footer={[
          <Button key="close" onClick={handleClose}>
            关闭
          </Button>,
          <Button
            key="generate"
            type="primary"
            icon={<IconRobot />}
            loading={loading}
            disabled={loading}
            onClick={handleGenerate}
          >
            {summary ? '重新生成' : '生成摘要'}
          </Button>,
        ]}
      >
        <Spin loading={loading} className="summary-content">
          {error ? (
            <Alert type="error" content={error} />
          ) : summary ? (
            <div className="summary-text">{summary}</div>
          ) : (
            <Empty description="点击下方按钮生成 AI 摘要" />
          )}
        </Spin>
      </Modal>
    );
  }
);

export default LlmSummaryPostDialog;

// frontend/src/components/llm/LlmSummaryPostDialog.vue
<script setup lang="ts">
import { ref, useImperativeHandle, forwardRef } from 'vue';
import { Modal, Button, lert, Empty, Spin, Message } from '@arco-design/web-vue';
import { IconRobot } from '@arco-design/web-vue/es/icon';
import * as llmChatApi from '@/api/llm/llmChat';

interface Props {
  title: string;
  content: string;
}

export interface LlmSummaryPostDialogRef {
  open: () => void;
}

const emit = defineEmits<{
  (e: 'open'): void;
}>();

const props = defineProps<Props>();

const visible = ref(false);
const loading = ref(false);
const summary = ref('');
const error = ref('');

defineExpose({
  open: () => {
    visible.value = true;
    error.value = '';
  },
});

const handleGenerate = async () => {
  if (!props.title || !props.content) {
    Message.warning('文章标题或内容为空');
    return;
  }

  loading.value = true;
  error.value = '';
  summary.value = '';

  try {
    const response = await llmChatApi.generatePostSummary(props.title, props.content);
    summary.value = response.summary;
    Message.success('AI 摘要生成成功');
  } catch (err) {
    console.error('生成 AI 摘要失败:', err);
    error.value = '生成摘要失败，请稍后重试';
    Message.error('生成摘要失败');
  } finally {
    loading.value = false;
  }
};

const handleClose = () => {
  visible.value = false;
  summary.value = '';
  error.value = '';
};
</script>

<template>
  <Modal
    title="AI 文章摘要"
    :visible="visible"
    @cancel="handleClose"
    :footer="[
      { key: 'close', render: () => h(Button, { onClick: handleClose }, { default: () => '关闭' }) },
      { key: 'generate', render: () => h(Button, { type: 'primary', icon: IconRobot, loading, disabled: loading, onClick: handleGenerate }, { default: () => (summary ? '重新生成' : '生成摘要') }) },
    ]"
  >
    <Spin :loading="loading" className="summary-content">
      <Alert v-if="error" type="error" :content="error" />
      <div v-else-if="summary" className="summary-text">{{ summary }}</div>
      <Empty v-else description="点击下方按钮生成 AI 摘要" />
    </Spin>
  </Modal>
</template>
