// frontend/src/pages/NotFound.tsx
import { useNavigate } from 'react-router-dom'
import { Button } from '@arco-design/web-react'
import './NotFound.css'

export default function NotFound() {
  const navigate = useNavigate()

  const goHome = () => {
    navigate('/')
  }

  return (
    <div className="not-found-container">
      <h1>404</h1>
      <p>抱歉，您访问的页面不存在。</p>
      <Button type="primary" onClick={goHome}>返回首页</Button>
    </div>
  )
}

// frontend/src/pages/NotFound.vue
<template>
  <div className="not-found-container">
    <h1>404</h1>
    <p>抱歉，您访问的页面不存在。</p>
    <a-button type="primary" @click="goHome">返回首页</a-button>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import './NotFound.css'

const router = useRouter()

const goHome = () => {
  router.push('/')
}
</script>
